services:
     clickhouse_cyg:
       build: .
       restart: 'no'
       volumes:
         - /Users/anastasialavruhina/feat-extr/output:/data
       user: "1015:1015"
       cpus: 28
       environment:
         - RUST_BACKTRACE=1


    
#networks:
#  clickhouse:
#    external: true
