services:
     clickhouse_cyg:
       build: .
       restart: 'no'
       volumes:
         - /home/lavrukhina/feat-extr/output:/data
       user: "1016:1016"
       cpus: 28
       environment:
         - RUST_BACKTRACE=1


    
#networks:
#  clickhouse:
#    external: true
